-- 1. 为 config 表添加 rss 列 (如果不存在)
ALTER TABLE public.config 
ADD COLUMN IF NOT EXISTS rss TEXT;

-- 2. 更新 Elon Musk 的 RSS 链接
UPDATE public.config
SET rss = 'https://news.google.com/rss/search?q=Elon+Musk&hl=en-US&gl=US&ceid=US:en'
WHERE slug = 'elon-musk';

-- 3. 确保 analyst_reports 表存在
CREATE TABLE IF NOT EXISTS public.analyst_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_slug TEXT NOT NULL,
  summary TEXT,
  sentiment_score FLOAT,
  sentiment_label TEXT,
  key_events TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 确保 dynamics 表存在
CREATE TABLE IF NOT EXISTS public.dynamics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_slug TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    source TEXT,
    url TEXT UNIQUE,
    pub_date TIMESTAMP WITH TIME ZONE,
    sentiment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. 刷新 Schema Cache (Supabase 有时需要重载)
NOTIFY pgrst, 'reload config';
