-- Enable Row Level Security (RLS) is recommended, but for public read access:

-- 1. CONFIG TABLE
-- Ensure table exists (you already created it, but good to double check structure)
-- CREATE TABLE IF NOT EXISTS public.config (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   slug TEXT UNIQUE NOT NULL,
--   name TEXT NOT NULL,
--   type TEXT,
--   heatindex TEXT,
--   trend TEXT,
--   stocksymbol TEXT,
--   tags TEXT,
--   summary TEXT,
--   rss TEXT,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );

-- ENABLE PUBLIC READ ACCESS
ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on config"
ON public.config
FOR SELECT
TO anon
USING (true);

-- 2. DYNAMICS TABLE
-- Ensure table exists
-- CREATE TABLE IF NOT EXISTS public.dynamics (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   entity_slug TEXT NOT NULL,
--   title TEXT NOT NULL,
--   summary TEXT,
--   source TEXT,
--   url TEXT,
--   pub_date TIMESTAMP WITH TIME ZONE,
--   sentiment TEXT,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );

-- ADD UNIQUE CONSTRAINT ON URL TO PREVENT DUPLICATES
ALTER TABLE public.dynamics ADD CONSTRAINT dynamics_url_key UNIQUE (url);

-- ENABLE PUBLIC READ ACCESS
ALTER TABLE public.dynamics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on dynamics"
ON public.dynamics
FOR SELECT
TO anon
USING (true);

-- 3. ANALYST REPORTS TABLE
CREATE TABLE IF NOT EXISTS public.analyst_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_slug TEXT NOT NULL,
  summary TEXT NOT NULL,
  sentiment_score FLOAT,
  sentiment_label TEXT,
  key_events TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ENABLE PUBLIC READ ACCESS
ALTER TABLE public.analyst_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on analyst_reports"
ON public.analyst_reports
FOR SELECT
TO anon
USING (true);
