import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import KeyInsightCards from './visualizations/KeyInsightCards';
import StrategicRadar from './visualizations/StrategicRadar';
import InventoryDonut from './visualizations/InventoryDonut';
import LogicFlow from '../../components/LogicFlow';

interface ReportViewProps {
  report: any;
}

export default function ReportView({ report }: ReportViewProps) {
  // Data extraction with safety checks
  const vizData = report?.visualization_data || {};
  const structData = report?.structured_data || {};

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 to-black text-white p-4 sm:p-6 lg:p-8">
      <div className="mx-auto max-w-7xl">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-500">
            Strategic Intelligence Report
          </h1>
          <p className="text-gray-400 mt-2">
            {report?.report_title || 'Comprehensive Market Analysis'}
          </p>
        </div>

        {/* Top Section: Key Insight Cards */}
        <section className="mb-6">
          <KeyInsightCards
            riskScore={structData.risk_score || 0}
            heatIndex={structData.heat_index || 0}
            impactScore={structData.impact_score || 0}
          />
        </section>

        {/* Middle Section: Visualization Grid */}
        <section className="grid grid-cols-1 md:grid-cols-2 gap-6 my-6 min-h-[400px]">
          <div className="bg-gray-900/50 rounded-xl p-4 border border-white/5 backdrop-blur-sm h-[400px]">
             <StrategicRadar data={vizData.radar_data || []} />
          </div>
          <div className="bg-gray-900/50 rounded-xl p-4 border border-white/5 backdrop-blur-sm h-[400px]">
             <InventoryDonut data={vizData.inventory_mix || []} />
          </div>
        </section>

        {/* Bottom Section: Logic Flow and Full Report */}
        <section className="my-6">
          <div className="bg-gradient-to-br from-gray-900 to-gray-950 border border-gray-800 rounded-xl p-6 shadow-lg mb-6">
            <h3 className="text-lg font-semibold text-gray-200 mb-4">Analysis Logic Flow</h3>
            <div className="h-[400px] w-full">
              <LogicFlow code={report?.mermaid_code} />
            </div>
          </div>

          {/* Full Strategy Briefing */}
          <details className="mt-6 bg-gradient-to-br from-gray-900 to-gray-950 border border-gray-800 rounded-xl overflow-hidden group">
            <summary className="p-4 font-medium text-white cursor-pointer flex items-center gap-2 hover:bg-gray-800/50 transition-colors select-none">
              <span className="text-lg group-open:rotate-90 transition-transform duration-200">▶</span>
              <span className="text-lg">📜</span>
              View Full Strategy Briefing
            </summary>
            <div className="p-6 border-t border-gray-800">
              <div className="prose prose-invert max-w-none prose-headings:text-cyan-400 prose-a:text-purple-400">
                {report?.full_markdown_report ? (
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {report.full_markdown_report}
                  </ReactMarkdown>
                ) : (
                  <p className="text-gray-400">No detailed report available</p>
                )}
              </div>
            </div>
          </details>
        </section>

        {/* Footer */}
        <footer className="mt-12 pt-6 border-t border-gray-800 text-center text-gray-500 text-sm">
          <p>Strategic Intelligence Report • Generated by AI Analysis Engine</p>
          <p className="mt-1">{new Date().toLocaleDateString()}</p>
        </footer>
      </div>
    </div>
  );
}